# Best Numpy Functions for Data Science (50+)
[Original article](https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50)

### Contents 
1. [Array](#1)
1. [Linspace](#2)
1. [Arange](#3)
1. [Uniform Samples](#4)
1. [Random.randint](#5)
1. [Random.random](#6)
1. [Logspace](#7)
1. [Array of zero](#8)
1. [Array of Ones](#9)
1. [Array of k Random Value](#10)
1. [Identity](#11)
1. [Min](#12)
1. [Max](#13)
1. [Unique](#14)
1. [Mean](#15)
1. [Median](#16)
1. [Digitize](#17)
1. [Reshape](#18)
1. [Expand Dimensions](#19)
1. [Squeeze](#20)
1. [Count Non-Zero](#21)
1. [argwhere](#22)
1. [argmax & argmin](#23)
1. [Sort](#24)
1. [Abs](#25)
1. [Round](#26)
1. [Clip](#27)
1. [Where](#28)
1. [Put](#29)
1. [Copyto](#30)
1. [Retrieve Common Elements](#31)
1. [Difference](#32)
1. [Extracts Unique Elements From Both Arrays](#33)
1. [Union](#34)
1. [Horizontal Split](#35)
1. [Vertical Split](#36)
1. [Horizontal Stacking](#37)
1. [Vertical Stacking](#38)
1. [allclose](#39)
1. [Repeat](#40)
1. [tile](#41)
1. [Einsum](#42)
1. [Histogram](#43)
1. [Percentile](#44)
1. [Standard Deviation and Variance](#45)
1. [Show Floats With Two Decimal Values](#46)
1. [Prints Array To Its Max](#47)
1. [Increase The Number of Elements In a Line](#48)
1. [Save](#49)
1. [Load](#50)

---

In [1]:
# import all necessary modules
import numpy as np
import pandas as pd

---

### Array Creation methods

#### 1. Array <a id=1></a>
Creates array from scratch. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.array.html)  
```python
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```

**Important params:**  
`dtype`: desired data type for the resultant array.  
`ndim`: specify the minimum number of dimensions for the resultant array.  

**See also:**  
[`np.empty`](https://numpy.org/doc/1.26/reference/generated/numpy.empty.html) Returns a new uninitialized array.  
[`np.ones`](https://numpy.org/doc/1.26/reference/generated/numpy.ones.html)  Returns a new array setting values to one.  
[`np.zeros`](https://numpy.org/doc/1.26/reference/generated/numpy.zeros.html) Return a new array setting values to zero.  
[`np.full`](https://numpy.org/doc/1.26/reference/generated/numpy.full.html) Return a new array of given shape filled with value.  



In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 2. Linspace  <a id=2></a>
Creates an array with evenly spaced float numbers over a specified interval. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.linspace.html)  
```python
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```
**Important params:**  
`start`: starting index.  
`end`: last index.  
`num`: number of samples to generate.  

In [4]:
np.linspace(10, 100, 10, dtype="int32")

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
np.linspace(0, 4, 9)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

#### 3. Arange  <a id=3></a>
Return evenly spaced integer values over a given interval with some step size. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.arange.html)  
```python
np.arange(start, stop, step, dtype=None, *, like=None)
```
**Important params:**  
`step`: Space between values.  

In [6]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

#### 4. Uniform samples  <a id=4></a>
Generate a random sample from a uniform distribution between lower and higher limit values. [Official docs](https://numpy.org/doc/1.26/reference/random/generated/numpy.random.uniform.html)  
```python
np.random.uniform(low=0.0, high=1.0, size=None)
```

In [7]:
np.random.uniform(5, 10, size=5)

array([5.07952644, 6.98362797, 7.94970133, 5.42195331, 6.48178978])

In [8]:
np.random.uniform(-1, 1, size=(2, 3))

array([[ 0.0849129 , -0.81957586,  0.71925625],
       [-0.32771489,  0.47391389, -0.23595731]])

#### 5. Random randint  <a id=5></a>
Generate n random integer samples within a range. [Official docs](https://numpy.org/doc/1.26/reference/random/generated/numpy.random.randint.html)

```python
np.random.randint(low, high=None, size=None, dtype=int)
```

In [9]:
np.random.randint(-4, 4, size=(2, 2))

array([[-4, -1],
       [ 0, -2]])

#### 6. Random.random  <a id=6></a>
Generate n random float samples. [Official docs](https://numpy.org/doc/1.26/reference/random/generated/numpy.random.random.html)  

```python
np.random(size=None)
```

In [10]:
np.random.random(size=(1, 2))

array([[0.71623261, 0.79127061]])

#### 7. Logspace  <a id=7></a>
Generate evenly spaced numbers on a log scale. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.logspace.html)  
```python
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
```
**Important params:**  
`start`: starting value of sequence.  
`stop`: last value of sequence.  
`endpoint`: if True, the last sample will be included in the sequence.  
`base`: The base of log space. default is 10.

In [11]:
np.logspace(0, 10, 5, base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

#### 8. Array of zeros  <a id=8></a>
Creates array filled with zeros. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.zeros.html)  
```python
np.zeros(shape, dtype=float, order="C")
```
**Important params:**  
`shape`: shape of resultant array.  
`dtype`: desired data type of resultant array.  

In [12]:
np.zeros((3, 3), dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### 9. Array of ones <a id=9></a>
Creates array filled with ones. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.ones.html)  
```python
np.ones(shape, dtype=None, order="C")
```

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 10. Array filled with other number  <a id=10></a>
Creates array filled with a given value. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.full.html)  
```python
np.full(shape, fill_value, dtype=None)
```
**Important params:**  
`fill_value`: random value to fill inside the array.  

In [14]:
np.full((2, 4), 3.4)

array([[3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4]])

#### 11. Identity  <a id=11></a>
Create an identity matrix with specified dimensions. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.identity.html)  
```python
np.identity(n, dtype=None)
```

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

### Array operations

#### 12. Min  <a id=12></a>
Return the minimum value from the array. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.min.html)  
```python
np.min(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
```
**Important params:**  
`axis`: axis along which to operate.  
`out`: alternative array to store the output.  

In [16]:
arr = np.random.randint(-4, 4, size=(3, 3))
print(arr)
np.min(arr)

[[ 0  0  0]
 [-4 -4 -3]
 [ 0  3  2]]


-4

#### 13. Max  <a id=13></a>
Return the maximum value from the array. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.max.html)  
```python
np.max(a, axis=None, out=None)
```

In [17]:
np.max(arr)

3

#### 14. Unique  <a id=14></a>
Return an array with all the unique elements sorted. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.unique.html)  
```python
np.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
```
**Important params:**  
`return_index`: if True, return the indices of the array.  
`return_invers`: if True, return the indices of the unique array.  
`return_counts` : if True, return the number of times each unique element appears inside the arry.  
`axis`: The axis to operate on. By default, the array is considered flatted.

In [18]:
np.unique(arr, return_counts=True)

(array([-4, -3,  0,  2,  3]), array([2, 1, 4, 1, 1], dtype=int64))

#### 15. Mean  <a id=15></a>
It is used to get the mean of the array. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.mean.html)  
```python
np.mean(a, axis=None, dtype=None, out=None)
```

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr)

3.5

In [20]:
np.mean(arr, axis=1)

array([2., 5.])

#### 16. Median  <a id=16></a>
Return the median value of the array. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.median.html)  
```python
np.median(a, axis=None, out=None)
```

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.median(arr)

3.5

#### 17. Digitize  <a id=17></a>
Return the indices of the bins to which each value in the input array belongs. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.digitize.html)  
```python
np.digitize(x, bins, right=False)
```
**Important params:**  
`bins`: Array of bins.  
`right`: Indicates whether the interval includes the right or left bin edge.

In [22]:
a = np.array([-0.9, 0.5, 0.9, 1, 1.2, 1.4, 3.6, 4.7, 5.3])
bins = np.array([0, 1, 2, 3])
np.digitize(a, bins)

array([0, 1, 1, 2, 2, 2, 4, 4, 4], dtype=int64)

```
Exp        Value
x < 0     :   0
0 <= x <1 :   1
1 <= x <2 :   2
2 <= x <3 :   3
3 <=x     :   4
Compares -0.9 to 0, here x < 0 so Put 0 in resulting array.
Compares  0.5 to 0, here 0 <= x <1 so Put 1.
.
Compares 5.4 to 4, here 3<=x so Put 4

```

#### 18. Reshape  <a id=18></a>
It is one of the most used functions of NumPy. It Returns an array containing the same data with a new shape. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.reshape.html)  
```python
np.reshape(a, newshape, order="C")
```

In [23]:
A = np.random.randint(15,size=(4,3))
A, A.reshape(2, 6)

(array([[ 2,  7,  1],
        [ 8,  4,  7],
        [14, 11,  6],
        [ 5,  8,  2]]),
 array([[ 2,  7,  1,  8,  4,  7],
        [14, 11,  6,  5,  8,  2]]))

In [24]:
A.reshape(-1)

array([ 2,  7,  1,  8,  4,  7, 14, 11,  6,  5,  8,  2])

#### 19. Expand Dimensions  <a id=19></a>
It is used to expand the dimensions of an array. This method is useful for creating sample test data for testing a machine learning model. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.expand_dims.html)  
```python
np.expand_dims(a, axis)
```

In [25]:
arr = np.array([0, 14, 1, 8, 11, 4, 9, 4, 1, 13, 13, 11])
np.expand_dims(arr, axis=0)

array([[ 0, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11]])

In [26]:
np.expand_dims(arr, axis=1)

array([[ 0],
       [14],
       [ 1],
       [ 8],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [ 1],
       [13],
       [13],
       [11]])

#### 20. Squeeze  <a id=20></a>
Reduce the dimension of an array by removing single-dimensional entrie. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.squeeze.html)  
```python
np.squeeze(a, axis=None)
```

In [27]:
arr = np.array([[ 8],[14],[ 1],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

In [28]:
np.squeeze(arr, axis=1)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

#### 21. Count Non-Zero  <a id=21></a>
Count all the non-zero elements and return their count. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.count_nonzero.html)  
```python
np.count_nonzero(a, axis=None, *, keepdims=False)
```

In [29]:
a = np.array([0, 0, 1, 1, 1, 0])
np.count_nonzero(a)

3

In [30]:
a = np.array([[0, 1, 1], [0, 0, 0], [1, 0, 1]])
np.count_nonzero(a), np.count_nonzero(a, axis=1), np.count_nonzero(a, keepdims=True)

(4, array([2, 0, 2], dtype=int64), array([[4]], dtype=int64))

#### 22. Argwhere  <a id=22></a>
Find and return all the indices of non-zero elements. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.argwhere.html)  
```python
np.argwhere(a)
```

In [31]:
a = np.array([[0, 1, 1], [0, 0, 0], [1, 0, 1]])
np.argwhere(a)

array([[0, 1],
       [0, 2],
       [2, 0],
       [2, 2]], dtype=int64)

In [32]:
a = np.array([0, 0, 1, 1, 1, 0])
np.argwhere(a)

array([[2],
       [3],
       [4]], dtype=int64)

#### 23. Argmax & Argmin  <a id=23></a>
argmax returns the index of the max element from the array. It can be used to get the index of high probability predicted labels in multiclass image classification problems. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.argmax.html)  
```python
np.argmax(a, axis=None, out=None)
```

In [33]:
arr = np.array([[1, 5, 2, 19, 3], [3, 89, 12, 3, 1], [91, 65, 32, 1, 7]])
np.argmax(arr), np.argmax(arr, axis=0), np.argmax(arr, axis=1)

(10, array([2, 1, 2, 0, 2], dtype=int64), array([3, 1, 0], dtype=int64))

Argmin will return the index of the lowest element from the array. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.argmin.html)  
```python
np.argmin(a, axis=None, out=None)
```

In [34]:
np.argmin(arr), np.argmin(arr, axis=0), np.argmin(arr, axis=1)

(0, array([0, 0, 0, 2, 1], dtype=int64), array([0, 4, 3], dtype=int64))

#### 24. Sort  <a id=24></a>
Sort the array and return. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.sort.html)  
```python
np.sort(a, axis=-1, kind=None, order=None)
```
**Important params:**  
`kind`: Sorting algorithm to use. {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}  

In [35]:
arr = np.array([[1, 5, 2, 19, 3], [3, 89, 12, 3, 1], [91, 65, 32, 1, 7]])

In [36]:
np.sort(arr)

array([[ 1,  2,  3,  5, 19],
       [ 1,  3,  3, 12, 89],
       [ 1,  7, 32, 65, 91]])

In [37]:
np.sort(arr, axis=0)

array([[ 1,  5,  2,  1,  1],
       [ 3, 65, 12,  3,  3],
       [91, 89, 32, 19,  7]])

#### 25. Abs  <a id=25></a>
Return the absolute values of elements inside an array. It is useful when an array contains negative values.  [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.absolute.html)  


In [38]:
arr = np.array([[1, -3, 14, -10, 0], [-1, 49, 34, -17, 1]])
np.abs(arr)

array([[ 1,  3, 14, 10,  0],
       [ 1, 49, 34, 17,  1]])

#### 26. Round  <a id=26></a>
Round the float values to a specified number of decimal points. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.round.html)  
```python
np.round(a, decimals=0, out=None)
```
**Important params:**  
`decimals`: Number of decimals point to keep.

In [39]:
a = np.random.random(size=(2, 3))
a

array([[0.30649237, 0.74524832, 0.03261127],
       [0.25021029, 0.33667234, 0.72166717]])

In [40]:
np.round(a, decimals=0)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.round(a, decimals=1)

array([[0.3, 0.7, 0. ],
       [0.3, 0.3, 0.7]])

In [42]:
np.round(a, decimals=2)

array([[0.31, 0.75, 0.03],
       [0.25, 0.34, 0.72]])

#### 27. Clip  <a id=27></a>
It is used to keep the values of an array within a range. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.clip.html)  
```python
np.clip(a, a_min, a_max, out=None, **kwargs)
```
**Important params:**  
`a_min` and `a_max`: Minimum and maximum value. If None, clipping is not performed on the corresponding edge. Only one of them may be None.


In [43]:
arr = np.array([0, 1, -3, -4, 5, 6, 7, 2, 3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [44]:
arr.clip(-1, 3)

array([ 0,  1, -1, -1,  3,  3,  3,  2,  3])

---

### Replacing Values Inside Array  

#### 28. Where  <a id=28></a>
Return elements from an array where a condition satisfies. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.where.html)  
```python
np.where(condition, [x, y])
```
**Important params:**  
`condition`: condition to match. if true yield x otherwise y.  

In [45]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
np.where(a > 5)

(array([2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [47]:
a[np.where(a > 5)]

array([ 6,  7,  8,  9, 10, 11])

In [48]:
# get array of indeces
np.transpose(np.vstack(np.where(a > 5)))

array([[2, 0],
       [2, 1],
       [2, 2],
       [3, 0],
       [3, 1],
       [3, 2]], dtype=int64)

#### 29. Put  <a id=29></a>
Replaces specified elements of an array with given values. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.put.html)  
```python
np.put(a, ind, v)
```
**Important params:**  
`ind`: indices to be replaced.  
`v`: values to place.  

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [50]:
np.put(arr, [1, 2], [88, 99])
arr

array([ 1, 88, 99,  4,  5,  6,  7])

#### 30. Copyto  <a id=30></a>
Copy the content of one array into another. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.copyto.html)  
```python
np.copyto(dst, src, casting="same_kind", where=True)
```
**Important params:**  
`dst`: array into which values are copied.  
`src`: array from which values are copied.  

In [51]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1, arr2

(array([1, 2, 3]), array([4, 5, 6]))

In [52]:
np.copyto(arr1, arr2)
arr1, arr2

(array([4, 5, 6]), array([4, 5, 6]))

---

### Set Operations

#### 31. Retrieve Common Elements  <a id=31></a>
`np.intersect1d` function returns all the unique values from both arrays in a sorted manner. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.intersect1d.html)  
```python
np.intersect1d(ar1, ar2, assume_unique=False, return_indeces=False)
```
**Important params:**  
`assume_unique`: if true, then input arrays are both assumed to be unique.  
`return_indices`: if true, then common elements indices are returned.  

In [53]:
ar1 = np.array([1, 2, 3, 4, 5, 6])
ar2 = np.array([3, 4, 5, 8, 9, 1])
np.intersect1d(ar1, ar2)

array([1, 3, 4, 5])

In [54]:
np.intersect1d(ar1, ar2, return_indices=True)

(array([1, 3, 4, 5]),
 array([0, 2, 3, 4], dtype=int64),
 array([5, 0, 1, 2], dtype=int64))

#### 32. Difference  <a id=32></a>
`np.setdiff1d` function returns all the unique elements from arr1 that are not present in arr2. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.setdiff1d.html)  
```python
np.setdiff1d(ar1, ar2, assume_unique=False)
```

In [55]:
ar1 = np.array([1, 7, 3, 2, 4, 1])
ar2 = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(ar1, ar2)

array([1, 3, 4])

#### 33. Extracts Unique Elements From Both Arrays  <a id=33></a>
`np.setxor1d` function will return all the unique values from both arrays in sorted order. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.setxor1d.html)  
```python
np.setxor1d(ar1, ar2, assume_unique=False)
```

In [56]:
ar1 = np.array([1, 2, 3, 4, 6])
ar2 = np.array([1, 4, 9, 4, 36])
np.setxor1d(ar1, ar2)

array([ 2,  3,  6,  9, 36])

#### 34. Union  <a id=34></a>
`np.union1d` function will combine both arrays into one. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.union1d.html)  
```python
np.union1d(ar1, ar2)
```

In [57]:
ar1 = np.array([1, 2, 3, 4, 6])
ar2 = np.array([1, 4, 9, 4, 36])
np.union1d(ar1, ar2)

array([ 1,  2,  3,  4,  6,  9, 36])

---

### Splitting

#### 35. Horizontal Split  <a id=35></a>
`np.hsplit` function will split the data horizontally into n equal parts. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.hsplit.html)  
```python
np.hsplit(ary, indeces_or_sections)
```

In [58]:
arr = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(arr, 2)

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [59]:
np.hsplit(arr, [1, 2, 3])

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

In [60]:
np.hsplit(arr, [2, 3])

[array([[3, 4],
        [6, 7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

#### 36. Vertical Split  <a id=36></a>
`np.vsplit` will split the data vertically into n equal parts. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.vsplit.html)  
```python
np.vsplit(ary, indeces_or_sections)
```

In [61]:
np.vsplit(arr, 2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

---

### Stacking

#### 37. Horizontal stacking  <a id=37></a>
`np.hstack` will stack appends one array at the end of another. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.hstack.html)  
```python
np.hstack(tup, *, dtype=None, casting="same_kind")
```
**Important params:**  
`tup`: sequence of ndarrays.  

In [62]:
ar1 = np.array([1, 2, 3, 4, 5])
ar2 = np.array([1, 4, 9, 16, 25])
np.hstack((ar1, ar2))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

#### 38. Vertical stacking  <a id=38></a>
`np.vstack` will stack one array on top of another. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.vstack.html)  
```python
np.vstack(tup, *, dtype=None, casting="same_kind")
```

In [63]:
np.vstack((ar1, ar2))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

---

### Comparing Two Arrays

#### 39. Allclose  <a id=39></a>
`np.allclose` function finds whether two arrays are equal or approximately equal to each other based on some tolerance value if the shape of both arrays is the same. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.allclose.html)  
```python
np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
```
**Important params:**  
`rtol`: The relative tolerance parameter.  
`atol`: The absolute tolerance parameter.  
`equal_nan`: Whether to compare NaN’s as equal. If True, NaN’s in a will be considered equal to NaN’s in b in the output array.

In [89]:
a = np.array([0.25, 0.4, 0.6, 0.32])
b = np.array([0.26, 0.3, 0.7, 0.32])
tolerance = 0.1  # Total Difference 
np.allclose(a, b, tolerance)

False

In [65]:
tolerance = 0.5
np.allclose(a, b, tolerance)

True

#### 40. Repeat  <a id=40></a>
It is used to repeat elements of an array for n number of times. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.repeat.html)  
```python
np.repeat(a, repeats, axis=None)
```
**Important params:**  
`a`: element to repeat.  
`repeats`: number of times to repeat element.  

In [66]:
np.repeat("2023", 4)

array(['2023', '2023', '2023', '2023'], dtype='<U4')

In [67]:
arr = np.random.randint(0, 20, size=(3, 4))
arr

array([[ 0,  8,  9, 16],
       [16,  2, 17,  0],
       [ 7, 17,  1, 13]])

In [68]:
year = np.repeat(2020, 3)
year = np.expand_dims(year, axis=1)
arr = np.hstack((arr, year))
arr

array([[   0,    8,    9,   16, 2020],
       [  16,    2,   17,    0, 2020],
       [   7,   17,    1,   13, 2020]])

#### 41. Tile  <a id=41></a>
Construct an array by repeating A the number of times given by reps. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.tile.html)  
```python
np.tile(A, reps)
```

In [69]:
np.tile("Ram", 5)

array(['Ram', 'Ram', 'Ram', 'Ram', 'Ram'], dtype='<U3')

In [90]:
np.tile(3, (2, 3))

array([[3, 3, 3],
       [3, 3, 3]])

---

### Einstein Summation Conventions


#### 42. Einsum  <a id=42></a>
This function is used to compute many multi-dimensional and linear algebraic operations on arrays. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.einsum.html)  
```python
np.einsum(subscripts, *operands, out=None, dtype=None, order='K', casting='safe', optimize=False)
```


In [71]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(21, 30).reshape(3, 3)
a, b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]))

In [72]:
# extract diagonals
np.einsum("ii->i", a), np.einsum("ii->i", b)

(array([1, 5, 9]), array([21, 25, 29]))

In [73]:
# transpose
np.einsum("ji", a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [74]:
# matrix multipication
np.einsum("ij,jk", a, b)

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [75]:
# sum of diagonal
np.einsum("ii", a)

15

---

### Statistical Analysis


#### 43. Histogram  <a id=43></a>
It is an important statistical analysis function of NumPy that computes histogram values for a set of data. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.histogram.html)  
```python
numpy.histogram(a, bins=10, range=None, density=None, weights=None)
```


In [76]:
arr = np.array([[3, 4, 5, 2], [6, 7, 2, 6]])
np.histogram(arr)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1], dtype=int64),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))

#### 44. Percentile  <a id=44></a>
It computes the q-th percentile of the data along a specified axis. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.percentile.html)  
```python
np.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)

```

**Important params:**  
`q`: percentile to compute.  
`overwrite_input`: if true, then allow the input array to modify the intermediate calculation to save memory.  

In [77]:
a = np.array([[2, 4, 6], [4, 8, 12]])
np.percentile(a, 50)

5.0

In [78]:
np.percentile(a, 10)

3.0

#### 45. Standard Deviation and Variance  <a id=45></a>
`np.std` and `np.var` are two functions of NumPy that calculates standard deviation and variance along an axis. [Official docs (std)](https://numpy.org/doc/1.26/reference/generated/numpy.std.html) & [Official docs (var)](https://numpy.org/doc/1.26/reference/generated/numpy.var.html)
```python
np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
```
```python
np.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
```



In [79]:
a = np.array([[2, 4, 6], [4, 8, 12]])

In [80]:
np.std(a,axis=1)  # row wise

array([1.63299316, 3.26598632])

In [81]:
np.std(a,axis=0)  # column wise

array([1., 2., 3.])

In [82]:
np.var(a,axis=1)

array([ 2.66666667, 10.66666667])

In [83]:
np.var(a,axis=0)

array([1., 4., 9.])

---

### Array Printing Options


#### 46. Show Floats With Two Decimal Values  <a id=46></a>

In [84]:
np.set_printoptions(precision=2)
a = np.array([12.23456, 32.34535])
print(a)

[12.23 32.35]


#### 47. Prints Array To Its Max  <a id=47></a>

In [85]:
np.set_printoptions(threshold=np.inf)

#### 48. Increase The Number of Elements In a Line  <a id=48></a>


In [86]:
np.set_printoptions(linewidth=100)  # default 75

---

### Save and Load Array Data


#### 49. Save  <a id=49></a>
`np.savetxt` used to save the content of an array inside a text file. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.savetxt.html)  
```python
np.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
```

In [87]:
arr = np.linspace(10, 100, 500).reshape(25, 20) 
np.savetxt('some_files/array.txt', arr)

#### 50. Load  <a id=50></a>
`np.loadtxt` used to load the content of an array from a text file. It takes the file name as a parameter. [Official docs](https://numpy.org/doc/1.26/reference/generated/numpy.loadtxt.html)  
```python
np.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, 
           unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None)
```

In [88]:
np.loadtxt('some_files/array.txt')

array([[ 10.  ,  10.18,  10.36,  10.54,  10.72,  10.9 ,  11.08,  11.26,  11.44,  11.62,  11.8 ,
         11.98,  12.16,  12.34,  12.53,  12.71,  12.89,  13.07,  13.25,  13.43],
       [ 13.61,  13.79,  13.97,  14.15,  14.33,  14.51,  14.69,  14.87,  15.05,  15.23,  15.41,
         15.59,  15.77,  15.95,  16.13,  16.31,  16.49,  16.67,  16.85,  17.03],
       [ 17.21,  17.39,  17.58,  17.76,  17.94,  18.12,  18.3 ,  18.48,  18.66,  18.84,  19.02,
         19.2 ,  19.38,  19.56,  19.74,  19.92,  20.1 ,  20.28,  20.46,  20.64],
       [ 20.82,  21.  ,  21.18,  21.36,  21.54,  21.72,  21.9 ,  22.08,  22.26,  22.44,  22.63,
         22.81,  22.99,  23.17,  23.35,  23.53,  23.71,  23.89,  24.07,  24.25],
       [ 24.43,  24.61,  24.79,  24.97,  25.15,  25.33,  25.51,  25.69,  25.87,  26.05,  26.23,
         26.41,  26.59,  26.77,  26.95,  27.13,  27.31,  27.49,  27.68,  27.86],
       [ 28.04,  28.22,  28.4 ,  28.58,  28.76,  28.94,  29.12,  29.3 ,  29.48,  29.66,  29.84,
         30.02,  30