In [1]:
import numpy as np

### Basics

In [2]:
a = np.array([1, 2, 3], dtype="int16")
print(a)

[1 2 3]


In [3]:
b = np.array([[1.2, 5.2, 3.1], [6.2, 2.4, 2.5]])
print(b)

[[1.2 5.2 3.1]
 [6.2 2.4 2.5]]


In [4]:
# get dimension
a.ndim, b.ndim

(1, 2)

In [5]:
# get shape
a.shape, b.shape

((3,), (2, 3))

In [6]:
# get type
a.dtype, b.dtype

(dtype('int16'), dtype('float64'))

In [7]:
# get size (bytes)
a.itemsize, b.itemsize

(2, 8)

In [8]:
# get total size (amount of elements)
a.size, b.size

(3, 6)

In [9]:
# get total size
a.nbytes, b.nbytes

(6, 48)

### Accessing/Changing specific elements, rows, columns etc.

In [10]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [11]:
# get a specific element [r, c]
a[1, 5], a[1, -2], a[0, 0]

(13, 13, 1)

In [12]:
# get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# get specific column
a[:, 0]

array([1, 8])

In [14]:
# get specific part of matrix [startindex:endindex:stepsize]
a[0:2, ::2]

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14]])

In [15]:
a[1, 5] = 20
a[:, 4] = -3
a[:, 5:7] = [[0, 0], [0, 0]]
a

array([[ 1,  2,  3,  4, -3,  0,  0],
       [ 8,  9, 10, 11, -3,  0,  0]])

### Initializing Different Types of Arrays

In [16]:
# all 0z matrix
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# all 1s matrix
np.ones((1,3))

array([[1., 1., 1.]])

In [18]:
# any other number
np.full((2, 2), -1)

array([[-1, -1],
       [-1, -1]])

In [19]:
# any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [20]:
# random decimal numbers
np.random.rand(*a.shape)

array([[0.13577141, 0.79895964, 0.68890161, 0.08379883, 0.78671462,
        0.34691567, 0.97004567],
       [0.54278289, 0.30874386, 0.4704684 , 0.42702735, 0.08661523,
        0.75416244, 0.45688274]])

In [21]:
# random integer numbers
np.random.randint(3, 11, size=(3, 3))

array([[10,  5,  4],
       [ 8, 10,  6],
       [ 8,  3,  8]])

In [22]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
# copy matrix
barr = arr.copy()
barr[0, 1] = -99
barr, arr

(array([[  1, -99,   3]]), array([[1, 2, 3]]))

#### Example

In [25]:
output = np.ones((5, 5))
mid = np.identity(3) * 9
output[1:4, 1:4] = mid
output

array([[1., 1., 1., 1., 1.],
       [1., 9., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 9., 1.],
       [1., 1., 1., 1., 1.]])

### Mathematics

In [26]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [27]:
a + 2

array([3, 4, 5, 6])

In [28]:
a * 2

array([2, 4, 6, 8])

In [29]:
a - 10

array([-9, -8, -7, -6])

In [30]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [31]:
a ** 2

array([ 1,  4,  9, 16])

In [32]:
# take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [33]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)

In [34]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [35]:
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [36]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

In [37]:
np.min(stats, axis=1)

array([1, 4])

In [38]:
np.max(stats)

6

In [39]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing arrays

In [40]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [41]:
before.reshape(8, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [42]:
# vertically/horizontally stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2]), np.hstack([v1, v2])

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([1, 2, 3, 4, 5, 6, 7, 8]))

### Miscellaneous

#### Load data from file

In [43]:
filedata = np.genfromtxt("some_files/example_txt.txt", delimiter=",")
filedata = filedata.astype("int32")
filedata

array([[1, 2, 5, 3, 1, 8, 2, 8, 9, 1],
       [9, 6, 8, 2, 1, 9, 1, 5, 3, 2],
       [1, 6, 3, 8, 3, 9, 2, 2, 5, 4],
       [3, 9, 5, 4, 8, 2, 9, 2, 3, 3]], dtype=int32)

#### Boolean masking and advanced indexing

In [44]:
(filedata > 5).astype("int16")

array([[0, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 0, 0]], dtype=int16)

In [45]:
# bool mask
filedata[filedata > 7]

array([8, 8, 9, 9, 8, 9, 8, 9, 9, 8, 9], dtype=int32)

In [46]:
# indexing with list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 6, 8]]

array([2, 7, 9])

In [47]:
np.any(filedata > 5, axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [48]:
np.all(filedata < 5, axis=0)

array([False, False, False, False, False, False, False, False, False,
        True])

In [49]:
((filedata > 5) & (filedata < 8)).astype("int16")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)