In [1]:
import numpy as np

In [2]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.random((2, 2))

array([[0.69419534, 0.13813155],
       [0.53860843, 0.94015473]])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.linspace(0, 10, 20).reshape(4, 5)

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316],
       [ 2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211],
       [ 5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105],
       [ 7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]])

In [8]:
np.random.randint(-10, 10, size=(2, 4))

array([[ 5,  8,  1, -9],
       [ 3,  2,  7, -7]])

In [9]:
shape = (3, 4)
a = np.random.randint(0, 2, size=shape)
b = np.empty(shape)
np.copyto(b, a)
b

array([[0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [1., 0., 0., 1.]])

In [10]:
arr = np.random.randint(-5, 5, size=(3, 5))
arr

array([[-3,  3,  2, -4, -5],
       [-4, -5, -4,  1,  1],
       [-5,  3, -2,  0,  4]])

In [11]:
np.sum(arr)

-18

In [12]:
np.mean(arr)

-1.2

In [13]:
np.std(arr)

3.208322510804257

In [14]:
np.median(arr)

-2.0

In [15]:
np.max(arr), np.min(arr)

(4, -5)

In [16]:
shape = (3, 7)
arr = np.random.randint(0, 10, size=shape)
arr

array([[3, 3, 8, 3, 5, 1, 7],
       [5, 8, 3, 0, 0, 3, 0],
       [7, 6, 6, 9, 2, 2, 4]])

In [17]:
# sort all items in ascending order
sorted_arr = arr.flatten()
sorted_arr = np.sort(sorted_arr)
sorted_arr = sorted_arr.reshape(shape)
sorted_arr

array([[0, 0, 0, 1, 2, 2, 3],
       [3, 3, 3, 3, 4, 5, 5],
       [6, 6, 7, 7, 8, 8, 9]])

In [18]:
# find max index
amx = np.argmax(arr)
mx_idx = (amx // 7, amx % 7)
mx_idx, arr[mx_idx]

((2, 3), 9)

In [19]:
shape1 = (3, 5)
ar1 = np.random.randint(0, 10, size=shape1)
shape2 = (5, 4)
ar2 = np.random.randint(0, 10, size=shape2)
ar1, ar2

(array([[5, 1, 2, 3, 5],
        [4, 3, 7, 7, 6],
        [5, 8, 2, 3, 2]]),
 array([[7, 1, 6, 3],
        [3, 6, 8, 5],
        [7, 2, 2, 3],
        [2, 4, 7, 6],
        [4, 7, 2, 2]]))

In [20]:
np.dot(ar1, ar2)

array([[ 78,  62,  73,  54],
       [124, 106, 123, 102],
       [ 87,  83, 123,  83]])

In [21]:
ar1.T.shape

(5, 3)

In [22]:
ar1.flatten(), ar2.flatten()

(array([5, 1, 2, 3, 5, 4, 3, 7, 7, 6, 5, 8, 2, 3, 2]),
 array([7, 1, 6, 3, 3, 6, 8, 5, 7, 2, 2, 3, 2, 4, 7, 6, 4, 7, 2, 2]))

In [32]:
np.hstack((ar1.T, ar2))

array([[5, 4, 5, 7, 1, 6, 3],
       [1, 3, 8, 3, 6, 8, 5],
       [2, 7, 2, 7, 2, 2, 3],
       [3, 7, 3, 2, 4, 7, 6],
       [5, 6, 2, 4, 7, 2, 2]])

In [34]:
np.concatenate((ar1.T, ar2), axis=1)

array([[5, 4, 5, 7, 1, 6, 3],
       [1, 3, 8, 3, 6, 8, 5],
       [2, 7, 2, 7, 2, 2, 3],
       [3, 7, 3, 2, 4, 7, 6],
       [5, 6, 2, 4, 7, 2, 2]])

In [47]:
np.split(ar1, indices_or_sections=[1], axis=1)

[array([[5],
        [4],
        [5]]),
 array([[1, 2, 3, 5],
        [3, 7, 7, 6],
        [8, 2, 3, 2]])]

In [49]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
np.diagonal(arr)

array([ 1,  6, 11, 16])

In [53]:
"""
4x - 2y = 22
6x + y = 45
"""
a = np.array([[4, -2], [6, 1]])
b = np.array([22, 45])
np.linalg.solve(a, b)

array([7., 3.])

In [54]:
shape = (4, 6)
a = np.random.randint(1, 34, size=shape)
b = np.random.randint(1, 34, size=shape)
a, b

(array([[ 3, 33, 14, 22, 18, 27],
        [17, 17,  5,  6, 24, 29],
        [25, 23, 31, 24, 29,  5],
        [28,  3, 24,  5, 15, 26]]),
 array([[32, 31, 15, 10, 27, 12],
        [ 8, 24, 21, 20,  3,  4],
        [18, 16, 15,  1, 30, 21],
        [20, 25, 25,  1, 27,  1]]))

In [55]:
a + b

array([[35, 64, 29, 32, 45, 39],
       [25, 41, 26, 26, 27, 33],
       [43, 39, 46, 25, 59, 26],
       [48, 28, 49,  6, 42, 27]])

In [56]:
a - b

array([[-29,   2,  -1,  12,  -9,  15],
       [  9,  -7, -16, -14,  21,  25],
       [  7,   7,  16,  23,  -1, -16],
       [  8, -22,  -1,   4, -12,  25]])

In [57]:
a * b

array([[  96, 1023,  210,  220,  486,  324],
       [ 136,  408,  105,  120,   72,  116],
       [ 450,  368,  465,   24,  870,  105],
       [ 560,   75,  600,    5,  405,   26]])

In [58]:
a / b

array([[ 0.09375   ,  1.06451613,  0.93333333,  2.2       ,  0.66666667,
         2.25      ],
       [ 2.125     ,  0.70833333,  0.23809524,  0.3       ,  8.        ,
         7.25      ],
       [ 1.38888889,  1.4375    ,  2.06666667, 24.        ,  0.96666667,
         0.23809524],
       [ 1.4       ,  0.12      ,  0.96      ,  5.        ,  0.55555556,
        26.        ]])

In [59]:
a @ b.T

array([[2359, 1712, 1921, 1770],
       [2202,  957, 1988, 1573],
       [3061, 1990, 2282, 2662],
       [2116, 1049, 1913, 1671]])

In [60]:
a > 10

array([[False,  True,  True,  True,  True,  True],
       [ True,  True, False, False,  True,  True],
       [ True,  True,  True,  True,  True, False],
       [ True, False,  True, False,  True,  True]])

In [62]:
np.sum((a > 10).astype("int32"))

18

In [64]:
np.unique(a, return_counts=True)

(array([ 3,  5,  6, 14, 15, 17, 18, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33]),
 array([2, 3, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1], dtype=int64))

In [65]:
a < b

array([[ True, False,  True, False,  True, False],
       [False,  True,  True,  True, False, False],
       [False, False, False, False,  True,  True],
       [False,  True,  True, False,  True, False]])